#$Id: Makefile,v 1.1 2009/07/30 09:56:11 dreamdaq Exp $

BINDIR		= $(HOME)/bin

APPS		= daq.sh dreamProc.sh osccleaner.sh takeCamScreenshots.sh

install:
	@mkdir -p $(BINDIR)
	/bin/cp -p $(APPS) $(BINDIR)/

