# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
# Kinematics: 
#
/run/printProgress 500
/gps/particle e-
/gps/energy 0.2 GeV
/gps/position 0 0 -160 cm
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 1.0 cm
/gps/ang/type beam1d
/gps/ang/sigma_r 0.1 deg
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/random/setSeeds 1.2 2.5
#
/run/beamOn 6000


