#!/bin/bash


NOCOL="\033[0m"
BLUFG="\033[1;34m"
YELFG="\033[1;33m"
YELBG="\033[1;43m"
BLUBG="\033[1;44m"
GREFG="\033[1;32m"
GREBG="\033[1;42m"
REDFG="\033[1;31m"
REDBG="\033[1;41m"
WHIFG="\033[1;37m"
WHIBG="\033[1;47m"
BLKFG="\033[1;30m"
BKLBG="\033[1;40m"
BLKFU="\033[4;30m"
PURFG="\033[1;35m"
ERROR="\033[5;7;31m"
WARNI="\033[5;7;33m"
TITLE="\033[2;7;30m"

WATCH=
if [ $# -eq 1 ]; then
  if [ $1 == "-w" ]; then
    WATCH=1
  fi
fi

ELAST=0
RLAST=0

monitor()
{
  echo -ne "$TITLE"; date; echo -ne "$NOCOL"
  BAR="--------------------------------------------------------------------------------"
  RUNNBR=`grep RunNumber ~/working/.dreamdaqrc | awk '{print $2}'`
  STTIME=`stat -c %z ~/working/.dreamdaqrc | colrm 20`
  EPOSTR=`stat -c %Z ~/working/.dreamdaqrc`
  EPONOW=`date +%s`
  let M=($EPONOW-$EPOSTR)/60
  let H=$M/60
  let M=$M%60

  STATUS="Running"
  ssh pcdreamus ps -C "myReadOutDrs4" | grep -q myReadOutDrs4
  if [ $? -ne 0 ]; then
    STATUS="${WARNI}[NOT RUNNING]${NOCOL}"
    ELAST=0
    RLAST=0
  fi

  echo "$BAR"
  echo -e "${REDFG}Run number: $RUNNBR  ${NOCOL}   $STATUS "
  echo -e "${NOCOL}Start time: ${NOCOL}$STTIME"
  echo -e "${NOCOL}Run time  : ${NOCOL}$H h $M min"
  echo "$BAR"

  echo -e "${BLUFG}Daq status:${NOCOL}"
  BUF=`grep Total ~/working/logfile.txt | tail -1` 
  SPILL=0
  SPILL=`echo $BUF | sed -e 's/.*End in ~ //' -e 's/spills.*//'`
  EVNTS=`echo $BUF | sed -e 's/.*Events //' -e 's/ (.*//' `
  let R=${EVNTS} - ${ELAST}
  if [ $R -gt 0 ]; then RLAST=$R; else R=$RLAST; fi
  if [ $ELAST -eq 0 ]; then R=0; fi
  ELAST=$EVNTS
  if [ $R -lt 100 ]; then echo -ne $WARNI ; fi
  echo -e  "\t    Rate = $R evt/spill$NOCOL" 
  echo -ne "\t    Spill # "
  echo "$BUF" | sed -e 's/--/\n\t   /g' | sed -e 's/ -/\n\t   /g' | grep -v time
  PRE=
  if [ $SPILL -lt 4 ]; then echo -e "\t    ${WARNI}Last $SPILL spills" $NOCOL
  else echo; fi
  echo "$BAR"

  echo -e "${GREFG}Data files: ${NOCOL}"
  ls -lh ~/working/data/datafile_run${RUNNBR}*        2>/dev/null | colrm 1 25 | awk '{print "\t   " $0}' 
  echo -e "${GREFG}Pedestals : ${NOCOL}"
  ls -lh ~/working/pedestal/pedestal_run${RUNNBR}*    2>/dev/null | colrm 1 25 | awk '{print "\t   " $0}' 
  echo -e "${GREFG}Histograms: ${NOCOL}"
  ls -lh ~/working/hbook/datafile_histo_run${RUNNBR}* 2>/dev/null | colrm 1 25 | awk '{print "\t    " $0}' 
  echo "$BAR"

  DISKW=`df -h /mnt/working | grep mnt`
  DISKB=`df -h /mnt/wd      | grep mnt`
  DISKW_OCC=`echo $DISKW | tr '%' ' ' | awk '/mnt/ {print $5}'`
  DISKB_OCC=`echo $DISKB | tr '%' ' ' | awk '/mnt/ {print $5}'`
  DISKW_WARN=
  DISKB_WARN=
  if [ $DISKW_OCC -gt 94 ]; then DISKW_WARN="${ERROR}Storage disk almost full${NOCOL}"; fi
  if [ $DISKB_OCC -gt 94 ]; then DISKB_WARN="${ERROR}Backup disk almost full${NOCOL}";  fi
  echo -e "${PURFG}Disk usage: ${NOCOL}"
  echo -e "\t   ${DISKW} ${DISKW_WARN}"
  echo -e "\t   ${DISKB} ${DISKB_WARN}"
  echo "$BAR"


#  echo -e  "${BLKFG}Processes: ${NOCOL}"
#  ssh pcdreamus "ps -C 'sampler myReadOut myDataWriter myReadOutDrs4' -o pid,pcpu,pmem,rss,bsdtime,command"  
#                    | column -t  | awk '{print "            " $0}'

}

if [ $WATCH ]; then
  while true; do clear; monitor; sleep 20; done
else
  monitor
fi
